In [1]:
import pandas as pd

In [8]:
df = pd.read_excel('/Users/harshith/Desktop/untitled folder 2/interns3.xlsx')

In [9]:
df = pd.DataFrame(df)

In [10]:
df

,position,title,snippet,highlighs,link,displayed_link,sitelinks
0,0,BLR Airport,"Jul 31, 2023 — ... food & beverages, staff ser...","['food', 'beverages', 'Kempegowda Internationa...",https://twitter.com/BLRAirport/status/16859091...,https://twitter.com › BLRAirport › status,NaN
1,1,BLR Airport,"Aug 3, 2022 — has opened a new outlet at Depar...",['food'],https://twitter.com/BLRAirport/status/15546804...,https://twitter.com › BLRAirport › status,NaN
2,2,anshul gupta,"Sep 25, 2023 — Bangalore airport also earns 70...","['Bangalore airport', 'Food and beverages']",https://twitter.com/anshgupta64/status/1706514...,https://twitter.com › anshgupta64 › status,NaN
3,3,Bangalore Mirror,"Dec 15, 2020 — The Quad retail and food and be...","['food and beverage', 'Kempegowda Internationa...",https://twitter.com/bangaloremirror/status/133...,https://twitter.com › bangaloremirror › status,NaN
4,4,BLR Airport - Bengaluru,"Oct 23, 2021 — #BLRAirport for the live screen...",['food and beverages'],https://twitter.com/blrairport/status/14518810...,https://twitter.com › blrairport › status,NaN
...,...,...,...,...,...,...,...
87,87,In_Sane_Saint - Ashish Jain,Start Up Idea: Flight service from Bangalore A...,"['Flight', 'Bangalore Airport', 'Bangalore', '...",https://twitter.com/In_Sane_Saint,https://twitter.com › In_Sane_Saint,NaN
88,88,Ravi Handa,"Sep 9, 2022 — 5 years ago, they used to be coo...",['food'],https://twitter.com/ravihanda/status/156822205...,https://twitter.com › ravihanda › status,"{'inline': [{'title': 'bangalore', 'link': 'ht..."
89,89,Narendra Modi,"Nov 11, 2022 — Terminal 2 of the Kempegowda In...","['Kempegowda International Airport', 'Bengaluru']",https://twitter.com/narendramodi/status/159099...,https://twitter.com › narendramodi › status,"{'inline': [{'title': '""food', 'link': 'https:..."
90,90,Harvesting Farmer Network (HFN),"Apr 12, 2020 — Partial movement is allowed for...","['food', 'Bangalore airport']",https://twitter.com/HarvestingFN/status/124928...,https://twitter.com › HarvestingFN › status,NaN
91,91,DashHound - X.com,"Aug 31, 2023 — Cheers from the International L...","['International', 'Bangalore airport', 'flight']",https://twitter.com/DashHound7/status/16972887...,https://twitter.com › DashHound7 › status,"{'inline': [{'title': '""food', 'link': 'https:..."

In [11]:
df.describe()

       position
count  92.00000
mean   45.50000
std    26.70206
min     0.00000
25%    22.75000
50%    45.50000
75%    68.25000
max    91.00000

In [12]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
87    False
88    False
89    False
90    False
91    False
Length: 92, dtype: bool

In [13]:
df=df.drop(columns=['position','title','link','displayed_link','sitelinks'])

In [14]:
df

,snippet,highlighs
0,"Jul 31, 2023 — ... food & beverages, staff ser...","['food', 'beverages', 'Kempegowda Internationa..."
1,"Aug 3, 2022 — has opened a new outlet at Depar...",['food']
2,"Sep 25, 2023 — Bangalore airport also earns 70...","['Bangalore airport', 'Food and beverages']"
3,"Dec 15, 2020 — The Quad retail and food and be...","['food and beverage', 'Kempegowda Internationa..."
4,"Oct 23, 2021 — #BLRAirport for the live screen...",['food and beverages']
...,...,...
87,Start Up Idea: Flight service from Bangalore A...,"['Flight', 'Bangalore Airport', 'Bangalore', '..."
88,"Sep 9, 2022 — 5 years ago, they used to be coo...",['food']
89,"Nov 11, 2022 — Terminal 2 of the Kempegowda In...","['Kempegowda International Airport', 'Bengaluru']"
90,"Apr 12, 2020 — Partial movement is allowed for...","['food', 'Bangalore airport']"
91,"Aug 31, 2023 — Cheers from the International L...","['International', 'Bangalore airport', 'flight']"

In [15]:
df['highlighs']==''

0     False
1     False
2     False
3     False
4     False
      ...
87    False
88    False
89    False
90    False
91    False
Name: highlighs, Length: 92, dtype: bool

In [16]:
df.to_excel('/Users/harshith/Desktop/untitled folder 2/interns_new.xlsx',index=False)

In [17]:
df2=pd.read_excel('/Users/harshith/Desktop/untitled folder 2/interns2.xlsx')

In [18]:
df2=pd.DataFrame(df2)

In [19]:
df2

,position,title,snippet,highlighs,link,displayed_link,sitelinks
0,0,Taj Bangalore - Twitter,"May 22, 2019 — Dive into the luxury and unmatc...","['hospitality', 'Bangalore', 'Kempegowda Inter...",https://twitter.com/TajBangalore/status/113112...,https://twitter.com › TajBangalore › status,NaN
1,1,Taj Bangalore (@TajBangalore) / ...,Taj Bangalore is a mere walk away from the Kem...,"['Bangalore', 'International Airport', 'hotel'...",https://twitter.com/TajBangalore,https://twitter.com › TajBangalore,NaN
2,2,Aviserv,"Sep 14, 2018 — We're offering a full range of ...","['Hospitality', 'airport']",https://twitter.com/AviservOfficial/status/104...,https://twitter.com › AviservOfficial › status,NaN
3,3,Aviserv,"Sep 14, 2018 — We're offering a full range of ...","['Hospitality', 'airport']",https://twitter.com/aviservofficial/status/104...,https://twitter.com › aviservofficial › status,NaN
4,4,Red Key (@RedKey94155390) / Twitter,Red Key is a budget-friendly 2-star hotel in B...,"['hotel in Bangalore', 'Airport', 'hospitality']",https://www.twitter.com/RedKey94155390,https://www.twitter.com › RedKey94155390,NaN
...,...,...,...,...,...,...,...
94,94,Sunderdeep - Volklub,Bangalore Auto Driver. Embedded video. 0:25. 2...,"['Bangalore', 'airport']",https://twitter.com/volklub,https://twitter.com › volklub,NaN
95,95,vishwanath somapur (@vishwanath1241) / Twitter,⁩ and staff of HBX airport for hospitality at ...,"['airport', 'hospitality', 'flight', 'Bangalor...",https://twitter.com/vishwanath1241?lang=es,https://twitter.com › vishwanath1241,"{'inline': [{'title': 'Translate this page', '..."
96,96,Musthafa PC (@Musthafa_PC) / Twitter,"... Bangalore factory today, 30th March, at 12...","['Bangalore', 'airport']",https://twitter.com/musthafa_pc?lang=eu,https://twitter.com › musthafa_pc,NaN
97,97,Blessen Babu (@blessn_official) / Twitter,#swiggy is down in Bangalore. Image. 1. Blesse...,"['Bangalore', 'flight', 'hospitality']",https://twitter.com/blessn_official,https://twitter.com › blessn_official,NaN
98,98,Bengaluru Airport City receives IGBC Green ......,Bengaluru Airport City receives IGBC Green Cit...,"['Bengaluru Airport', 'Bengaluru']",https://mobile.twitter.com/ChristinMP_/status/...,https://mobile.twitter.com › ChristinMP_ › status,"{'inline': [{'title': '""hospitality', 'link': ..."

In [20]:
df2=df2.drop(columns=['position','title','link','displayed_link','sitelinks'])

In [21]:
df2

,snippet,highlighs
0,"May 22, 2019 — Dive into the luxury and unmatc...","['hospitality', 'Bangalore', 'Kempegowda Inter..."
1,Taj Bangalore is a mere walk away from the Kem...,"['Bangalore', 'International Airport', 'hotel'..."
2,"Sep 14, 2018 — We're offering a full range of ...","['Hospitality', 'airport']"
3,"Sep 14, 2018 — We're offering a full range of ...","['Hospitality', 'airport']"
4,Red Key is a budget-friendly 2-star hotel in B...,"['hotel in Bangalore', 'Airport', 'hospitality']"
...,...,...
94,Bangalore Auto Driver. Embedded video. 0:25. 2...,"['Bangalore', 'airport']"
95,⁩ and staff of HBX airport for hospitality at ...,"['airport', 'hospitality', 'flight', 'Bangalor..."
96,"... Bangalore factory today, 30th March, at 12...","['Bangalore', 'airport']"
97,#swiggy is down in Bangalore. Image. 1. Blesse...,"['Bangalore', 'flight', 'hospitality']"
98,Bengaluru Airport City receives IGBC Green Cit...,"['Bengaluru Airport', 'Bengaluru']"

In [22]:
df2.duplicated()

0     False
1     False
2     False
3      True
4     False
      ...
94    False
95    False
96    False
97    False
98    False
Length: 99, dtype: bool

In [23]:
df2.drop_duplicates()

,snippet,highlighs
0,"May 22, 2019 — Dive into the luxury and unmatc...","['hospitality', 'Bangalore', 'Kempegowda Inter..."
1,Taj Bangalore is a mere walk away from the Kem...,"['Bangalore', 'International Airport', 'hotel'..."
2,"Sep 14, 2018 — We're offering a full range of ...","['Hospitality', 'airport']"
4,Red Key is a budget-friendly 2-star hotel in B...,"['hotel in Bangalore', 'Airport', 'hospitality']"
5,Hotel Golden Evana provides hotel close to Ban...,"['Hotel', 'hotel', 'Bangalore airport']"
...,...,...
94,Bangalore Auto Driver. Embedded video. 0:25. 2...,"['Bangalore', 'airport']"
95,⁩ and staff of HBX airport for hospitality at ...,"['airport', 'hospitality', 'flight', 'Bangalor..."
96,"... Bangalore factory today, 30th March, at 12...","['Bangalore', 'airport']"
97,#swiggy is down in Bangalore. Image. 1. Blesse...,"['Bangalore', 'flight', 'hospitality']"
98,Bengaluru Airport City receives IGBC Green Cit...,"['Bengaluru Airport', 'Bengaluru']"

In [24]:
df2.dropna(inplace=True)

In [25]:
df2

,snippet,highlighs
0,"May 22, 2019 — Dive into the luxury and unmatc...","['hospitality', 'Bangalore', 'Kempegowda Inter..."
1,Taj Bangalore is a mere walk away from the Kem...,"['Bangalore', 'International Airport', 'hotel'..."
2,"Sep 14, 2018 — We're offering a full range of ...","['Hospitality', 'airport']"
3,"Sep 14, 2018 — We're offering a full range of ...","['Hospitality', 'airport']"
4,Red Key is a budget-friendly 2-star hotel in B...,"['hotel in Bangalore', 'Airport', 'hospitality']"
...,...,...
94,Bangalore Auto Driver. Embedded video. 0:25. 2...,"['Bangalore', 'airport']"
95,⁩ and staff of HBX airport for hospitality at ...,"['airport', 'hospitality', 'flight', 'Bangalor..."
96,"... Bangalore factory today, 30th March, at 12...","['Bangalore', 'airport']"
97,#swiggy is down in Bangalore. Image. 1. Blesse...,"['Bangalore', 'flight', 'hospitality']"
98,Bengaluru Airport City receives IGBC Green Cit...,"['Bengaluru Airport', 'Bengaluru']"

In [26]:
df2.loc[:,"highlighs"]

0     ['hospitality', 'Bangalore', 'Kempegowda Inter...
1     ['Bangalore', 'International Airport', 'hotel'...
2                            ['Hospitality', 'airport']
3                            ['Hospitality', 'airport']
4      ['hotel in Bangalore', 'Airport', 'hospitality']
                            ...
94                             ['Bangalore', 'airport']
95    ['airport', 'hospitality', 'flight', 'Bangalor...
96                             ['Bangalore', 'airport']
97               ['Bangalore', 'flight', 'hospitality']
98                   ['Bengaluru Airport', 'Bengaluru']
Name: highlighs, Length: 98, dtype: object

In [42]:
df2.to_excel('/Users/harshith/Desktop/untitled folder 2/interns2_new.xlsx',index=False)

In [43]:
df3=pd.read_excel('/Users/harshith/Desktop/untitled folder 2/interns1.xlsx')

In [44]:
df3

,position,title,snippet,highlighs,link,displayed_link,sitelinks
0,0,BLR Airport,"Dec 15, 2022 — Some media have reported that B...","['BLR Airport', 'Immigration', 'airport']",https://twitter.com/BLRAirport/status/16033533...,https://twitter.com › BLRAirport › status,NaN
1,1,Immigration Chaos at Bengaluru Airport. 8 coun...,"May 23, 2022 — Immigration Chaos at Bengaluru ...","['Immigration', 'Bengaluru Airport']",https://twitter.com/petleepeter/status/1528614...,https://twitter.com › petleepeter › status,NaN
2,2,Kiran Mazumdar-Shaw,"May 21, 2022 — Pathetic state of immigration a...","['immigration', 'Bengaluru International Airpo...",https://twitter.com/kiranshaw/status/152820084...,https://twitter.com › kiranshaw › status,NaN
3,3,Pranava Tandra,3AM immigration queues at Bangalore Airport. I...,"['immigration', 'Bangalore Airport']",https://twitter.com/pranavatandra/status/15949...,https://twitter.com › pranavatandra › status,NaN
4,4,Harsh Goenka,"May 23, 2022 — Scenes in immigration in the Be...","['immigration', 'Bengaluru airport', 'internat...",https://twitter.com/hvgoenka/status/1528644476...,https://twitter.com › hvgoenka › status,NaN
...,...,...,...,...,...,...,...
94,94,Ravi Kumar (@Ravi_Author) / X,Entertainment & Recreation Bangalore ravikumar...,"['Bangalore', 'immigration', 'airport']",https://twitter.com/Ravi_Author,https://twitter.com › Ravi_Author,NaN
95,95,卫纳夜格.巴特 Col Vinayak Bhat (Retd) @Raj47,"May 16, 2018 — #India #Bengaluru #Bellandur #L...","['Bengaluru', 'airport', 'immigrants']",https://twitter.com/rajfortyseven/status/99665...,https://twitter.com › rajfortyseven › status,NaN
96,96,Flyers can bid goodbye to traffic jams and tak...,"Feb 9, 2018 — ... AIRPORT(http://taal.co.in) w...","['AIRPORT', 'Bangalore']",https://twitter.com/jayantsinha/status/9618792...,https://twitter.com › jayantsinha › status,NaN
97,97,تويتر \ Tarang (Tarang_97@),The immigration officer at the Ahmd airport no...,"['immigration', 'airport', 'Karnataka', 'Banga...",https://twitter.com/tarang_97?lang=ar-x-fm,https://twitter.com › tarang_97,"{'inline': [{'title': 'Translate this page', '..."
98,98,تويتر \ Siddharth Behera (imseed@),(chennai - Bangalore 6E6137). I ... The great ...,"['Bangalore', 'immigration', 'airport']",https://twitter.com/imseed?lang=ar-x-fm,https://twitter.com › imseed,"{'inline': [{'title': 'Translate this page', '..."

In [45]:
df3=df3.drop(columns=["position","title","link","displayed_link","sitelinks"])

In [46]:
df3

,snippet,highlighs
0,"Dec 15, 2022 — Some media have reported that B...","['BLR Airport', 'Immigration', 'airport']"
1,"May 23, 2022 — Immigration Chaos at Bengaluru ...","['Immigration', 'Bengaluru Airport']"
2,"May 21, 2022 — Pathetic state of immigration a...","['immigration', 'Bengaluru International Airpo..."
3,3AM immigration queues at Bangalore Airport. I...,"['immigration', 'Bangalore Airport']"
4,"May 23, 2022 — Scenes in immigration in the Be...","['immigration', 'Bengaluru airport', 'internat..."
...,...,...
94,Entertainment & Recreation Bangalore ravikumar...,"['Bangalore', 'immigration', 'airport']"
95,"May 16, 2018 — #India #Bengaluru #Bellandur #L...","['Bengaluru', 'airport', 'immigrants']"
96,"Feb 9, 2018 — ... AIRPORT(http://taal.co.in) w...","['AIRPORT', 'Bangalore']"
97,The immigration officer at the Ahmd airport no...,"['immigration', 'airport', 'Karnataka', 'Banga..."
98,(chennai - Bangalore 6E6137). I ... The great ...,"['Bangalore', 'immigration', 'airport']"

In [47]:
df3.dropna(inplace=True)

In [48]:
df3

,snippet,highlighs
0,"Dec 15, 2022 — Some media have reported that B...","['BLR Airport', 'Immigration', 'airport']"
1,"May 23, 2022 — Immigration Chaos at Bengaluru ...","['Immigration', 'Bengaluru Airport']"
2,"May 21, 2022 — Pathetic state of immigration a...","['immigration', 'Bengaluru International Airpo..."
3,3AM immigration queues at Bangalore Airport. I...,"['immigration', 'Bangalore Airport']"
4,"May 23, 2022 — Scenes in immigration in the Be...","['immigration', 'Bengaluru airport', 'internat..."
...,...,...
94,Entertainment & Recreation Bangalore ravikumar...,"['Bangalore', 'immigration', 'airport']"
95,"May 16, 2018 — #India #Bengaluru #Bellandur #L...","['Bengaluru', 'airport', 'immigrants']"
96,"Feb 9, 2018 — ... AIRPORT(http://taal.co.in) w...","['AIRPORT', 'Bangalore']"
97,The immigration officer at the Ahmd airport no...,"['immigration', 'airport', 'Karnataka', 'Banga..."
98,(chennai - Bangalore 6E6137). I ... The great ...,"['Bangalore', 'immigration', 'airport']"

In [49]:
df.to_excel('/Users/harshith/Desktop/untitled folder 2/interns1_new.xlsx',index=False)